In [1]:
from google .colab import files
uploaded=files. upload()

Saving abc.csv to abc.csv

In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("abc.csv")
df

<ipython-input-4-1353f1dc3b13>:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("abc.csv")

,Registrar,Enrolment Agency,State,District,Sub District,Pin Code,Gender,Age,Aadhaar generated,Enrolment Rejected,Residents providing email,Residents providing mobile number
0,Allahabad Bank,A-Onerealtors Pvt Ltd,Uttar Pradesh,Allahabad,Meja,212303,F,7,1,0,0,1
1,Allahabad Bank,Asha Security Guard Services,Uttar Pradesh,Sonbhadra,Robertsganj,231213,M,8,1,0,0,0
2,Allahabad Bank,SGS INDIA PVT LTD,Uttar Pradesh,Sultanpur,Sultanpur,227812,F,13,1,0,0,1
3,Allahabad Bank,Sri Ramraja Sarkar Lok Kalyan Trust,Uttar Pradesh,Shamli,Shamli,247775,M,6,1,0,0,1
4,Allahabad Bank,Transmoovers India,Uttar Pradesh,Gorakhpur,Sahjanwa,273001,M,8,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
440813,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,1,3,0,0,1
440814,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,2,1,0,0,1
440815,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,3,3,0,0,1
440816,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,4,1,0,0,0
440817,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Ranchi,Ranchi,834002,F,3,1,0,0,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440818 entries, 0 to 440817
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Registrar                          440818 non-null  object
 1   Enrolment Agency                   440818 non-null  object
 2   State                              440818 non-null  object
 3   District                           440818 non-null  object
 4   Sub District                       440818 non-null  object
 5   Pin Code                           440818 non-null  object
 6   Gender                             440818 non-null  object
 7   Age                                440818 non-null  int64
 8   Aadhaar generated                  440818 non-null  int64
 9   Enrolment Rejected                 440818 non-null  int64
 10  Residents providing email          440818 non-null  int64
 11  Residents providing mobile number  440818 non-null  int64
dtypes: int64(5), object(7)
memory usage: 40.4+ MB

In [8]:
x=df.groupby('State')['Aadhaar generated'].sum()
x

State
Andaman and Nicobar Islands         5
Andhra Pradesh                   5798
Arunachal Pradesh                 913
Assam                            3213
Bihar                          162607
Chandigarh                        259
Chhattisgarh                     6604
Dadra and Nagar Haveli            140
Daman and Diu                     105
Delhi                            8426
Goa                              1167
Gujarat                         34844
Haryana                          6804
Himachal Pradesh                 1547
Jammu and Kashmir                1234
Jharkhand                        9868
Karnataka                       19764
Kerala                          15143
Lakshadweep                         4
Madhya Pradesh                  53276
Maharashtra                     26085
Manipur                          1323
Meghalaya                         277
Mizoram                          6279
Nagaland                          545
Odisha                          18182
Others                             12
Puducherry                         83
Punjab                           6506
Rajasthan                       39570
Sikkim                             50
Tamil Nadu                      32485
Telangana                        5018
Tripura                           908
Uttar Pradesh                  103767
Uttarakhand                     13227
West Bengal                    119901
Name: Aadhaar generated, dtype: int64

In [9]:
x=df.groupby('State')['Enrolment Rejected'].sum()
x

State
Andaman and Nicobar Islands       2
Andhra Pradesh                  373
Arunachal Pradesh                79
Assam                            28
Bihar                          7209
Chandigarh                        9
Chhattisgarh                    380
Dadra and Nagar Haveli            3
Daman and Diu                     2
Delhi                           591
Goa                             127
Gujarat                        2500
Haryana                         532
Himachal Pradesh                123
Jammu and Kashmir               204
Jharkhand                       477
Karnataka                      1445
Kerala                          538
Lakshadweep                       1
Madhya Pradesh                 3509
Maharashtra                    1818
Manipur                         190
Meghalaya                         2
Mizoram                         185
Nagaland                         43
Odisha                         1596
Others                            0
Puducherry                       10
Punjab                          421
Rajasthan                      2035
Sikkim                            2
Tamil Nadu                     1193
Telangana                       274
Tripura                          62
Uttar Pradesh                  5286
Uttarakhand                     955
West Bengal                    6372
Name: Enrolment Rejected, dtype: int64

In [11]:
x=df.groupby('District')['Aadhaar generated'].sum()
x

District
Adilabad         265
Agra            2283
Ahmadnagar       476
Ahmedabad       4212
Aizawl          1095
                ...
Wokha             32
Yadgir           325
Yamuna Nagar     197
Yavatmal         712
Zunheboto          8
Name: Aadhaar generated, Length: 664, dtype: int64

In [12]:
x=df.groupby('State')['Enrolment Rejected'].sum()
x

State
Andaman and Nicobar Islands       2
Andhra Pradesh                  373
Arunachal Pradesh                79
Assam                            28
Bihar                          7209
Chandigarh                        9
Chhattisgarh                    380
Dadra and Nagar Haveli            3
Daman and Diu                     2
Delhi                           591
Goa                             127
Gujarat                        2500
Haryana                         532
Himachal Pradesh                123
Jammu and Kashmir               204
Jharkhand                       477
Karnataka                      1445
Kerala                          538
Lakshadweep                       1
Madhya Pradesh                 3509
Maharashtra                    1818
Manipur                         190
Meghalaya                         2
Mizoram                         185
Nagaland                         43
Odisha                         1596
Others                            0
Puducherry                       10
Punjab                          421
Rajasthan                      2035
Sikkim                            2
Tamil Nadu                     1193
Telangana                       274
Tripura                          62
Uttar Pradesh                  5286
Uttarakhand                     955
West Bengal                    6372
Name: Enrolment Rejected, dtype: int64

In [13]:
df['Gender'].value_counts()

M    292798
F    148013
T         7
Name: Gender, dtype: int64

In [14]:
#count records based on age
x=df[df['Age']<25]
y=df[(df['Age']>=25) & (df['Age'] <= 35)]
z=df[df['Age']>45]

#counts
count_lessthan_25= len(x)
count_between_25_35=len(y)
count_greaterthan_45= len(z)
# print counts
print(f"count of records with age <25:{count_lessthan_25}")
print(f"count of records age between 25 and 35:{count_between_25_35}")
print(f"count of records with age >45:{count_greaterthan_45}")

count of records with age <25:296836
count of records age between 25 and 35:62512
count of records with age >45:50610