In [1]:
from google.colab import files# import data
uploaded= files.upload()

Saving Newyork.csv to Newyork.csv

In [2]:
import numpy as np# reading data anmd removing  duplicate header
import pandas as pd
df=pd.read_csv("Newyork.csv",header=1)
df

,FacilityName,FacilityAddress,Borough
0,Engine 4/Ladder 15,42 South Street,Manhattan
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan
2,Engine 6,49 Beekman Street,Manhattan
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
4,Ladder 8,14 North Moore Street,Manhattan
...,...,...,...
213,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue,Staten Island
214,Engine 167/Ladder 87,345 Annadale Road,Staten Island
215,Engine 164/Ladder 84,1560 Drumgoole Road West,Staten Island
216,Engine 168/EMS Station 23,1100 Rossville Avenue,Staten Island
217,Engine 151/Ladder 76,7219 Amboy Road,Staten Island

In [3]:
df.head()#first 5 rows

,FacilityName,FacilityAddress,Borough
0,Engine 4/Ladder 15,42 South Street,Manhattan
1,Engine 10/Ladder 10,124 Liberty Street,Manhattan
2,Engine 6,49 Beekman Street,Manhattan
3,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
4,Ladder 8,14 North Moore Street,Manhattan

In [4]:
df.info()# using info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FacilityName     218 non-null    object
 1   FacilityAddress  218 non-null    object
 2   Borough          218 non-null    object
dtypes: object(3)
memory usage: 5.2+ KB

In [5]:
df.describe()# statistical data

              FacilityName  FacilityAddress   Borough
count                  218              218       218
unique                 218              218         5
top     Engine 4/Ladder 15  42 South Street  Brooklyn
freq                     1                1        66

In [6]:
x=list(df.columns.values)# columns names
x

['FacilityName', 'FacilityAddress', 'Borough']

In [7]:
df.index# index of the data

RangeIndex(start=0, stop=218, step=1)

In [8]:
df.count()# cont of attributes

FacilityName       218
FacilityAddress    218
Borough            218
dtype: int64

In [9]:
df.dtypes# data types

FacilityName       object
FacilityAddress    object
Borough            object
dtype: object

In [10]:
df = pd.read_csv("Newyork.csv", index_col ="Borough",header=1)#select fdny info borough wise
df

,FacilityName,FacilityAddress
Borough,,
Manhattan,Engine 4/Ladder 15,42 South Street
Manhattan,Engine 10/Ladder 10,124 Liberty Street
Manhattan,Engine 6,49 Beekman Street
Manhattan,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street
Manhattan,Ladder 8,14 North Moore Street
...,...,...
Staten Island,Engine 162/Ladder 82/Battalion 23,256 Nelson Avenue
Staten Island,Engine 167/Ladder 87,345 Annadale Road
Staten Island,Engine 164/Ladder 84,1560 Drumgoole Road West
Staten Island,Engine 168/EMS Station 23,1100 Rossville Avenue
Staten Island,Engine 151/Ladder 76,7219 Amboy Road

In [11]:
df=pd.read_csv("Newyork.csv")#View fdny info for each borough
x=df.groupby('Borough').count()
x

               FacilityName  FacilityAddress
Borough
Borough                   1                1
Bronx                    34               34
Brooklyn                 66               66
Manhattan                48               48
Queens                   50               50
Staten Island            20               20

In [12]:
count_manhattan=df[df['Borough']=='Manhattan']#select fdny for manhattan
count_manhattan

,FacilityName,FacilityAddress,Borough
1,Engine 4/Ladder 15,42 South Street,Manhattan
2,Engine 10/Ladder 10,124 Liberty Street,Manhattan
3,Engine 6,49 Beekman Street,Manhattan
4,Engine 7/Ladder 1/Battalion 1/Manhattan Boroug...,100-104 Duane Street,Manhattan
5,Ladder 8,14 North Moore Street,Manhattan
6,Engine 9/Ladder 6,75 Canal Street,Manhattan
7,Engine 15/Ladder 18/Battalion 4,25 Pitt Street,Manhattan
8,Engine 28/Ladder 11,222 East 2nd Street,Manhattan
9,Engine 5,340 East 14th Street,Manhattan
10,Engine 55,363 Broome Street,Manhattan
11,Ladder 20/Division 1,253 Lafayette Street,Manhattan
12,Engine 24/Ladder 5/Battalion 2,227-29 6th Avenue,Manhattan
13,Engine 33/Ladder 9,42 Great Jones Street,Manhattan
14,Ladder 3/Battalion 6,108 East 13th Street,Manhattan
15,Squad 18,132 West 10th Street,Manhattan
16,Engine 34/Ladder 21,440 West 38th Street,Manhattan
17,Engine 26,220 West 37th Street,Manhattan
18,Engine 3/Ladder 12/Battalion 7,150 West 19th Street,Manhattan
19,Engine 1/Ladder 24,142-46 West 31st Street,Manhattan
20,Engine 14,14 East 18th Street,Manhattan
21,Engine 16 / Ladder 7,234 East 29th Street,Manhattan
22,Engine 21,238 East 40th Street,Manhattan
23,Engine 54/Ladder 4/Battalion 9,782 8th Avenue,Manhattan
24,Engine 23,215 West 58th Street,Manhattan
25,Rescue 1,530 West 43rd Street,Manhattan
26,Engine 40/Ladder 35,131 Amsterdam Avenue,Manhattan
27,Ladder 25/District Office 4/Division 3,205-207 West 77th Street,Manhattan
28,Engine 74,120 West 83rd Street,Manhattan
29,Engine 65,33 West 43rd Street,Manhattan
30,Engine 8 / Ladder 2 / Battalion 8,167 East 51st Street,Manhattan
31,Engine 39/Ladder 16,157-59 East 67th Street,Manhattan
32,Engine 44,221 East 75th Street,Manhattan
33,Engine 22/Ladder 13/Battalion 10,159 East 85th Street,Manhattan
34,Engine 58/Ladder 26,1367 5th Avenue,Manhattan
35,Engine 53/Ladder 43,1836-46 3rd Avenue,Manhattan
36,Engine 91,242 East 111th Street,Manhattan
37,Engine 35/Ladder 14,2282 3rd Avenue,Manhattan
38,Engine 76/Ladder 22/Battalion 11,145-51 West 100th Street,Manhattan
39,Engine 47,502 West 113th Street,Manhattan
40,Engine 59/Ladder 30,111 West 133rd Street,Manhattan
41,Engine 37/Ladder 40,415 West 125th Street,Manhattan
42,Engine 69/Ladder 28/Battalion 16,248 West 143rd Street,Manhattan
43,Engine 80/Ladder 23,503 West 139th Street,Manhattan
44,Engine 84/Ladder 34,513 West 161st Street,Manhattan
45,Engine 67,518 West 170th Street,Manhattan
46,Engine 93/Ladder 45/Battalion 13,515 West 181st Street,Manhattan
47,Engine 95/Ladder 36,29 Vermilyea Avenue,Manhattan
48,Marine 1,Little West 12th Street/Hudson River,Manhattan